version: "3.4"

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
volumes:
  node_modules: